# Etapa de build
FROM node:22 AS build
RUN rm -rf /usr/share/nginx/html/*
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --prod

# Etapa de producción con Nginx
FROM nginx:alpine
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
EXPOSE 80


