services:
  postgres:
    image: postgres:17
    container_name: postgres17
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: secreto
      POSTGRES_DB: midatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    image: node:22
    container_name: angular-dev
    working_dir: /app
    volumes:
      - ./frontend:/app # monta el código local 
      - /app/node_modules
    ports:
      - "4200:4200"
    command: sh -c "npm install -g @angular/cli && npm install && npm run start -- --host 0.0.0.0 --port 4200"

volumes:
    postgres_data:
