spring.application.name=backend
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/midatabase
spring.datasource.username=usuario
spring.datasource.password=secreto
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.jdbc.core=DEBUG